variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
trigger:
  branches:
    include:
    - refs/heads/master
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: YAML
  steps:
  - checkout: self
    fetchDepth: 1
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      ConnectedServiceName: 9b75a9d2-ea22-4eb5-b3a2-4e53e92ee2ab
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
      feedRestore: 693db751-c0d7-4a02-9171-cce04d582536
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      ConnectedServiceName: 9b75a9d2-ea22-4eb5-b3a2-4e53e92ee2ab
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    enabled: False
    inputs:
      ConnectedServiceName: 9b75a9d2-ea22-4eb5-b3a2-4e53e92ee2ab
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      ConnectedServiceName: 9b75a9d2-ea22-4eb5-b3a2-4e53e92ee2ab
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
